##应用名
spring: 
  application:
    name: webproject
  profiles:
    include:
      - lesson04
      - config
    
##服务配置
server: 
  port: 8888
  tomcat:
    min-spare-threads: 100
    accept-count: 1000
    max-threads: 1000
    max-connections: 5000
    connection-timeout: 10000
    uri-encoding: UTF-8
    basedir: /opt/logs/${spring.application.name}/${server.port}/
    
##日志配置
logging:
  path: ${server.tomcat.basedir}
  config: classpath:logging.xml
  level:
    root: INFO #TRACE < DEBUG < INFO < WARN < ERROR < FATAL

##系统相关配置
sys: 
  security: 
    #允许访问的来源配置，逗号隔开，*代表全部通过
    #allowAccessReferer: http://111.111.111.111,http://222.222.222.222
    allowAccessReferer: "*"
    